apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: bigdata-manager
type: Opaque
data:
  # 使用 echo -n 'your-password' | base64 生成这些值
  root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  user-password: YmlnZGF0YTEyMw==  # bigdata123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: bigdata-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: bigdata-manager
data:
  init.sql: |
    -- 这里放置初始化数据库的SQL脚本
    CREATE DATABASE IF NOT EXISTS bigdata_manager;
    USE bigdata_manager;
    -- 其他初始化SQL语句
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bigdata-manager
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: bigdata_manager
        - name: MYSQL_USER
          value: bigdata
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init-scripts
        configMap:
          name: mysql-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bigdata-manager
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None 